"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowRight, MessageSquareText } from "lucide-react";
export default function Register() {
  const router=useRouter(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [google,setGoogle]=useState(false);
  useEffect(()=>{fetch("/api/bootstrap").then(r=>r.json() as Promise<{googleAvailable?:boolean}>).then(d=>setGoogle(!!d.googleAvailable)).catch(()=>{})},[]);
  async function submit(e:React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { const r=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})}); const d=await r.json() as {error?:string}; if(!r.ok) throw new Error(d.error); router.push("/app"); router.refresh(); } catch(e) {setError(e instanceof Error?e.message:"No se pudo registrar");} finally {setBusy(false);} }
  return <main className="auth-page"><div className="auth-panel"><Link className="brand" href="/"><span className="brand-mark"><MessageSquareText size={21}/></span><span>nexo<span className="brand-dot">sms</span></span></Link><div className="auth-form"><div className="label">COMENZÁ ACÁ</div><h1>Creá tu cuenta.</h1><p>Tu plataforma SMS está a unos pasos.</p><form onSubmit={submit}><label>Nombre o empresa<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre de tu empresa"/></label><label>Correo electrónico<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@empresa.com"/></label><label>Contraseña<input type="password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 10 caracteres"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="btn btn-primary auth-submit" disabled={busy}>{busy?"Creando...":"Crear cuenta"}<ArrowRight size={18}/></button></form><div className="auth-divider"><span>o registrate con</span></div>{google?<a className="google-btn" href="/api/auth/google"><span>G</span> Google</a>:<div className="google-btn disabled"><span>G</span> Google · pendiente de configuración</div>}<p className="auth-switch">¿Ya tenés cuenta? <Link href="/login">Ingresá</Link></p></div><small className="auth-foot">© 2026 NexoSMS · Paraguay</small></div><div className="auth-aside"><div className="auth-pattern">SMS</div><div className="auth-quote">“Tu próximo mensaje puede llegar más lejos.”<span>Campañas, contactos y reportes en un solo lugar.</span></div></div></main>;
}
